services:

  jupyter: 
    environment:
      - JUPYTER_ENABLE_LAB=yes
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    ports:
      - 8888:8888

  mlflow-server:
    build:
      context: .
      dockerfile: ./docker/mlflow/Dockerfile
    environment:
      - MLFLOW_ARTIFACT_STORE=/home/artifacts
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/home/mlruns:rw
      - ./models:/home/artifacts:ro    
      