services:

  jupyter: 
    build: 
      context: .
      dockerfile: docker/jupyter/Dockerfile
    ports:
      - 8888:8888

    depends_on:
      - tracking_service

  tracking_service:
    image: ghcr.io/mlflow/mlflow:v2.20.1
    ports:
      - "8000:8000"
    environment:
      MLFLOW_BACKEND_STORE_URI : "sqlite:///mlflow/backend/mlflow.db"
      MLFLOW_HOST : "0.0.0.0"
      MLFLOW_PORT : "8000"
    volumes:
      - mlflow-backend-store:/mlflow/backend/
    command: ["mlflow", "server"]

volumes:
  mlflow-backend-store:    
      